language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database sige_test;' -U postgres

install:
  - php composer.phar install

script: phpunit --configuration tests/phpunit.xml
