language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database sige_test;' -U postgres
  - pg_restore --username "postgres" --dbname "sige_test" --no-password  --no-owner --no-privileges --no-tablespaces --verbose "db.backup/sige_test.backup"
  - mkdir public/captcha
  - chmod 777 public/captcha
  - mkdir library/HTMLPurifier/DefinitionCache/Serializer
  - chmod 777 library/HTMLPurifier/DefinitionCache/Serializer
  - chmod 777 application/cache/common

install:
  - php composer.phar install

script: phpunit --configuration tests/phpunit.xml
