web:
  image: nginx
  ports:
    - "8080:8080"
  volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/nginx/php.inc:/etc/nginx/conf.d/php.inc
    - ./docker/nginx/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
  volumes_from:
    - php
  links:
    - php

php:
  build: .
  container_name: sige-php
  volumes:
    - ./docker/php56/php.ini:/etc/php5/fpm/php.ini
    - ./docker/php56/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - .:/usr/share/nginx/html/site
  links:
    - pg

pg:
  build: ./docker/pg
  container_name: sige-pg
  ports:
    - "5434:5432"
  volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./docs/INSTALACAO/ddl-schema.sql:/docker-entrypoint-initdb.d/01-ddl-schema.sql
      - ./docs/INSTALACAO/ddl-dados-iniciais.sql:/docker-entrypoint-initdb.d/02-ddl-dados-iniciais.sql
